### ISSUE TITLE
Compatibility with Nette 2.3

### ISSUE THREAD

**Issue by miloshavlicek** [iPublikuj/gravatar#3]
User Deprecated:
Nette\Bridges\ApplicationLatte\Template::registerHelperLoader() is deprecated, use dynamic getLatte()->addFilter().

**Comment by akadlec** [comment]
Please create a pull request...

**Comment by miloshavlicek** [comment]
Ok

**Comment by akadlec** [comment]
Ok merged

**Comment by akadlec** [comment]
One thing. Registering helpers in the presenter/component like in readme file should be not necessary because of automatic registration: https://github.com/iPublikuj/gravatar/blob/master/src/IPub/Gravatar/DI/GravatarExtension.php#L58-L61
