### ISSUE TITLE
Nette 2.4

### ISSUE THREAD

**Issue by rasel-sk** [iPublikuj/gravatar#5]
Invoking filters via $template->getGravatarService($vars) is deprecated, use ($vars|getGravatarService)

Macros.php:
- Line 60: return $writer->write('echo %escape($template->getGravatarService()->buildUrl('. $arguments['email'] .', '. $arguments['size'] .'))');
- Line 79: return $writer->write('?> '. ($node->htmlNode->name === 'a' ? 'href' : 'src') .'="<?php echo %escape($template->getGravatarService()->buildUrl('. $arguments['email'] .', '. $arguments['size'] .'))?>" <?php');

**Comment by akadlec** [comment]
so could you create pull request?

**Comment by rasel-sk** [comment]
I'm not sure how ... maybe I set it up correctly...

**Comment by akadlec** [comment]
It is solved and new version is released
